batch_size: 32
cuda: 0
# data_path: 'data/physionet.org/files/slpdb/1.0.0/'
data_path: 'data/mesa/polysomnography/set2x10'
early_stop_delta: 0.001
early_stop_patience: 30
hz: 100
hz_rr: 5
lr: 0.001
lr_scheduler_patience: 10
max_epoch: 200
min_lr: 1e-6
seg_len_sec: 30
seg_len: -1
n_split: 10
n_class: 2
encoder:
  in_channels: 1
  channels: 128
  depth: 5
  reduced_size: 64
  out_channels: 32
  kernel_size: 5
  dropout: 0.3
  softplus_eps: 1.0e-4
  sd_output: true
decoder:
  k: 32
  width: -1
  in_channels: 64
  channels: 128
  depth: 5
  out_channels: 1
  kernel_size: 5
  gaussian_out: false
  softplus_eps: 1.0e-4
  dropout: 0.